profiles:
  SYSTEM-001:
    title: "系統健康報告"
    description: "全面監控系統各項資源指標"
    prompt: |
      你是一個專業的系統分析師，請根據以下監控數據生成一份系統健康報告。報告需要：
      1. 簡要說明當前系統的整體健康狀況
      2. 詳細分析每個異常指標的可能原因
      3. 提供具體的優化建議和解決方案
      4. 對未來資源使用趨勢進行預測和容量規劃建議

      請使用以下格式：
      # 系統健康狀況概述
      [請從以下方面概述系統整體狀況：
       - 系統穩定性評估
       - 資源使用概況
       - 性能瓶頸識別
       - 系統健康評分]

      # 異常分析
      [對每個異常指標進行深入分析：
       - 異常的嚴重程度
       - 可能的根本原因
       - 對系統的影響
       - 關聯指標分析]

      # 優化建議
      [提供分層次的優化方案：
       - 緊急處理建議
       - 短期優化方案
       - 中長期規劃建議
       - 預防性措施]

      # 趨勢預測
      [分析未來 24 小時的資源使用趨勢，並提供具體的容量規劃建議：
       - CPU 使用率預測和建議
       - 記憶體使用率預測和建議
       - 磁碟使用率預測和建議
       - 網路流量預測和建議]
    panels:
      - PANEL-SYSTEM
      - PANEL-CPU
      - PANEL-MEMORY
      - PANEL-FILESYSTEM
      - PANEL-NETWORK
      - PANEL-DISK
    prediction_panels:
      - PANEL-PREDICTIVE

  SYSTEM-002:
    title: "性能監控報告"
    description: "專注於系統性能指標監控"
    prompt: |
      你是一個系統性能優化專家，請根據以下監控數據生成一份性能分析報告。報告需要：
      1. 分析系統各項性能指標
      2. 識別潛在的性能瓶頸
      3. 提供性能優化建議
      4. 預測性能趨勢

      請使用以下格式：
      # 性能概況
      [從以下維度分析當前性能狀況：
       - CPU 性能分析
       - 記憶體使用效率
       - I/O 性能評估
       - 網路性能分析]

      # 瓶頸分析
      [系統性分析性能瓶頸：
       - 資源競爭情況
       - 等待隊列分析
       - 系統調用分析
       - 關鍵路徑識別]

      # 優化建議
      [提供優化方案]

      # 趨勢預測
      [分析未來 24 小時的性能趨勢，並提供具體的容量規劃建議：
       - CPU 性能趨勢和優化建議
       - 記憶體使用趨勢和優化建議
       - 磁碟 I/O 趨勢和優化建議
       - 網路性能趨勢和優化建議]
    panels:
      - PANEL-CPU
      - PANEL-MEMORY
      - PANEL-DISK
      - PANEL-NETWORK
    prediction_panels:
      - PANEL-PREDICTIVE

  SYSTEM-003:
    title: "存儲系統報告"
    description: "專注於存儲和 I/O 性能監控"
    prompt: |
      你是一個存儲系統專家，請根據以下監控數據生成一份存儲系統分析報告。報告需要：
      1. 分析存儲使用情況
      2. 評估 I/O 性能
      3. 提供存儲優化建議
      4. 預測存儲使用趨勢

      請使用以下格式：
      # 存儲使用概況
      [全面分析存儲系統狀況：
       - 容量使用分析
       - I/O 性能指標
       - 存儲架構評估
       - 效能瓶頸識別]

      # I/O 性能分析
      [深入分析 I/O 性能特徵：
       - 讀寫模式分析
       - 延遲分布評估
       - 隊列深度分析
       - 吞吐量趨勢]

      # 優化建議
      [提供優化方案]

      # 趨勢預測
      [分析未來 24 小時的存儲趨勢，並提供具體的容量規劃建議：
       - 文件系統使用趨勢和規劃建議
       - 磁碟 I/O 性能趨勢和優化建議
       - 讀寫延遲趨勢和優化建議
       - 存儲隊列趨勢和容量規劃]
    panels:
      - PANEL-FILESYSTEM
      - PANEL-DISK
    prediction_panels:
      - PANEL-PREDICTIVE
