{
 "title": "SPC_每日細節指標總覽",
 "tags": [ "spc" ],
 "time": { "from": "2025-04-09T04:00:00.500Z", "to": "2025-04-11T03:59:58.500Z" },
 "templating": {
  "list": [
   { "name": "spc_bucket", "label": "spc_bucket", "query": "spc" },
   { "name": "raw_bucket", "label": "raw_bucket", "query": "raw" },
   { "name": "measurement", "label": "measurement", "query": "pdu" },
   {
    "name": "fab",
    "label": "Fab",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"${spc_bucket}\",\n    tag: \"fab\",\n    predicate: (r) => true,\n    start: -90d\n)"
    }
   },
   {
    "name": "field",
    "label": "Metric",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.measurementFieldKeys(bucket: \"${spc_bucket}\", measurement: \"${measurement}\")"
    }
   },
   {
    "name": "pdu",
    "label": "PDU",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"${spc_bucket}\",\n    tag: \"name\",\n    predicate: (r) => r.fab == \"${fab}\" ,\n    start: -100d\n)"
    }
   },
   {
    "name": "bank",
    "label": "bank",
    "query": "L1-1,L1-2,L1-3,L2-1,L2-2,L2-3,L3-1,L3-2,L3-3"
   }
  ]
 },
 "panels": [
  { "title": "$pdu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pdu" },
  {
   "title": "資料更新日期",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_points\")\n  |> group()\n  |> last()\n  |> duplicate(column: \"_time\", as: \"_value\")\n  |> keep(columns: [\"_value\"])\n  |> last()\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"raw\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"name\"] == \"${pdu}\")\n // |> filter(fn: (r) => r[\"bank\"] == \"${bank}\")\n |> group(columns: [\"bank\"], mode:\"by\")\n\n\n"
    }
   ]
  },
  {
   "title": "目前選取 PDU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"${spc_bucket}\",\n    tag: \"name\",\n    predicate: (r) => r.fab == \"${fab}\" \n\n       and r.name == \"${pdu}\",\n    start: -90d\n)"
    }
   ]
  },
  {
   "title": "PR 異常規則比例分佈",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"name\"] == \"${pdu}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"pr2_counter\" or r[\"_field\"] == \"pr3_counter\" or r[\"_field\"] == \"pr1_counter\" or r[\"_field\"] == \"pr4_counter\" or r[\"_field\"] == \"pr5_counter\")\n  |> group(columns: [\"_field\"], mode:\"by\") \n  |> sum()\n  |> group(columns: [\"_field\"], mode:\"by\") \n  |> drop(columns: [\"_start\", \"_stop\"])\n      \n     \n  \n\n\n"
    }
   ]
  },
  {
   "title": "PR 異常事件每日統計時序圖",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"name\"] == \"${pdu}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pr3_flag\" or r[\"_field\"] == \"pr4_flag\" or r[\"_field\"] == \"pr2_flag\" or r[\"_field\"] == \"pr1_flag\" or r[\"_field\"] == \"pr5_flag\")\n  |> group(columns: [\"name\",\"_field\"])\n  |> aggregateWindow(every: 1h, fn: count )  \n \n  "
    }
   ]
  },
  {
   "title": "統計類",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nfrom(bucket: \"spc\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"name\"] == \"${pdu}\")\n  |> filter(fn: (r) => r[\"_field\"] !~ /flag/)\n  |> last()\n  |> schema.fieldsAsCols()\n  |> group()\n"
    }
   ]
  }
 ]
}