{
 "title": "SPC_每日異常指標總覽",
 "tags": [ "spc" ],
 "time": { "from": "2025-04-18T03:59:59.500Z", "to": "2025-04-19T03:59:58.500Z" },
 "templating": {
  "list": [
   { "name": "url", "label": "URL", "query": "localhost:3000" },
   { "name": "spc_bucket", "label": "spc_bucket", "query": "spc" },
   { "name": "raw_bucket", "label": "raw_bucket", "query": "raw" },
   { "name": "measurement", "label": "measurement", "query": "pdu" },
   {
    "name": "fab",
    "label": "Fab",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"${spc_bucket}\",\n    tag: \"fab\",\n    predicate: (r) => true,\n    start: -90d\n)"
    }
   },
   {
    "name": "pdu",
    "label": "PDU",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"${raw_bucket}\",\n    tag: \"name\",\n    predicate: (r) => r.fab == \"${fab}\",\n    start: -90d\n)"
    }
   },
   {
    "name": "field",
    "label": "Metric",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.measurementFieldKeys(bucket: \"${raw_bucket}\", measurement: \"${measurement}\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "資料更新日期",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_points\")\n  |> group()\n  |> last()\n  |> duplicate(column: \"_time\", as: \"_value\")\n  |> keep(columns: [\"_value\"])\n  |> last()\n"
    }
   ]
  },
  {
   "title": "製程 CP < 1 數量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cp\")\n  |> filter(fn: (r) => r[\"_value\"] < 1)\n  |> last()\n  |> group()\n  |> distinct(column: \"name\")\n  |> count(column: \"_value\")  \n"
    }
   ]
  },
  {
   "title": "製程 CPK < 1 數量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpk\")\n  |> filter(fn: (r) => r[\"_value\"] < 1.0)\n  |> last()\n  |> group()\n  |> distinct(column: \"name\")\n  |> count(column: \"_value\")  \n"
    }
   ]
  },
  {
   "title": "PR 觸發機率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => \n  r[\"_field\"] == \"pr1_rate\" or\n  r[\"_field\"] == \"pr2_rate\" or\n  r[\"_field\"] == \"pr3_rate\" or\n  r[\"_field\"] == \"pr4_rate\" or\n  r[\"_field\"] == \"pr5_rate\",\n  )\n // |> last()\n  |> group(columns: [\"_field\"], mode:\"by\") \n // |> mean()\n\n\n\n     \n  \n\n\n"
    }
   ]
  },
  {
   "title": "監控中 PDU 數量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "支" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: \"raw\", tag: \"name\",start: -90d)\n|> count(column: \"_value\")\n "
    }
   ]
  },
  {
   "title": "1 < CP < 1.33 數量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cp\")\n  |> filter(fn: (r) => r[\"_value\"] < 1.33 and r[\"_value\"] > 1.0)\n  |> last()\n  |> group()\n  |> distinct(column: \"name\")\n  |> count(column: \"_value\")   \n"
    }
   ]
  },
  {
   "title": "1 < CPK < 1.33 數量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${raw_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpk\")\n  |> filter(fn: (r) => r[\"_value\"] < 1.33 and r[\"_value\"] > 1.0)\n  |> last()\n  |> group()\n  |> distinct(column: \"name\")\n  |> count(column: \"_value\")  \n"
    }
   ]
  },
  {
   "title": "PDU 異常指標總表",
   "type": "table",
   "gridPos": { "h": 87, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nfrom(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n |> filter(fn: (r) => r[\"_field\"] == \"pr2_rate\" or r[\"_field\"] == \"pr3_rate\" or r[\"_field\"] == \"pr1_rate\" or r[\"_field\"] == \"pr4_rate\" or r[\"_field\"] == \"pr5_rate\" or r[\"_field\"] == \"quality_code\" or r[\"_field\"] == \"usl\" or r[\"_field\"] == \"ucl\" or r[\"_field\"] == \"ppk\" or r[\"_field\"] == \"pp\" or r[\"_field\"] == \"ooc_rate\" or r[\"_field\"] == \"min\" or r[\"_field\"] == \"max\" or r[\"_field\"] == \"lsl\" or r[\"_field\"] == \"lcl\" or r[\"_field\"] == \"cpk\" or r[\"_field\"] == \"cp\" or r[\"_field\"] == \"base_std\" or r[\"_field\"] == \"base_mean\")\n  |> map(fn: (r) => ({ r with _time: now() }))\n  |> group(columns: [\"_measurement\",\"name\", \"bank\",\"fab\",\"model\",\"_field\",\"_time\"])\n  //|> sum()\n  |> fill(column: \"_value\", value: 0.0)\n  |> schema.fieldsAsCols()\n  |>group()\n     \n\n"
    }
   ]
  }
 ]
}