{
 "title": "SPC_每月總覽",
 "tags": [ "spc" ],
 "time": { "from": "2025-04-16T16:00:00.000Z", "to": "2025-04-30T15:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "spc_bucket", "label": "spc_bucket", "query": "spc" },
   { "name": "raw_bucket", "label": "raw_bucket", "query": "raw" },
   { "name": "measurement", "label": "measurement", "query": "pdu" },
   {
    "name": "fab",
    "label": "Fab",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"${spc_bucket}\",\n    tag: \"fab\",\n    predicate: (r) => true,\n    start: -90d\n)"
    }
   },
   {
    "name": "field",
    "label": "Metric",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\nschema.measurementFieldKeys(bucket: \"${spc_bucket}\", measurement: \"${measurement}\")"
    }
   },
   {
    "name": "pdu",
    "label": "PDU",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"${spc_bucket}\",\n    tag: \"name\",\n    predicate: (r) => r.fab == \"${fab}\" ,\n    start: -100d\n)"
    }
   },
   {
    "name": "bank",
    "label": "bank",
    "query": "L1-1,L1-2,L1-3,L2-1,L2-2,L2-3,L3-1,L3-2,L3-3"
   }
  ]
 },
 "panels": [
  { "title": "總覽", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pdu" },
  {
   "title": "PR 異常規則比例分佈",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"name\"] == \"${pdu}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"pr2_counter\" or r[\"_field\"] == \"pr3_counter\" or r[\"_field\"] == \"pr1_counter\" or r[\"_field\"] == \"pr4_counter\" or r[\"_field\"] == \"pr5_counter\")\n  |> group(columns: [\"_field\"], mode:\"by\") \n  |> sum()\n  |> group(columns: [\"_field\"], mode:\"by\") \n  |> drop(columns: [\"_start\", \"_stop\"])\n      \n     \n  \n\n\n"
    }
   ]
  },
  {
   "title": "PR 異常事件每日統計時序圖",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"name\"] == \"${pdu}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pr3_counter\" or r[\"_field\"] == \"pr4_counter\" or r[\"_field\"] == \"pr2_counter\" or r[\"_field\"] == \"pr1_counter\" or r[\"_field\"] == \"pr5_counter\")\n  |> group(columns: [\"name\",\"_field\"])\n  |> aggregateWindow(every: 1d, fn: sum )  \n \n  "
    }
   ]
  },
  {
   "title": "電流時序圖",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"raw\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n  |> filter(fn: (r) => r[\"name\"] == \"${pdu}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current\")\n  |> aggregateWindow(every: 10m, fn: last, createEmpty: true)\n  |> group(columns: [\"bank\"])\n  |> keep(columns: [\"_time\", \"_value\", \"bank\"])\n"
    }
   ]
  },
  { "title": "每日電流範圍箱型統計圖", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "$pdu  - $bank",
   "type": "candlestick",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "repeat": "bank",
   "targets": [
    {
     "query": "from(bucket: \"${spc_bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pdu\")\n   |> filter(fn: (r) => r[\"name\"] == \"${pdu}\")\n      |> filter(fn: (r) => r[\"bank\"] == \"${bank}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\" or r[\"_field\"] == \"min\" or r[\"_field\"] == \"p25\" or r[\"_field\"] == \"p75\")\n"
    }
   ]
  }
 ]
}