INSERT INTO `jobs` (`type`, `key`, `value`) VALUES
	('FactorySyncGlobalEnv', 'Enable', 'true'),
	('FactorySyncGlobalEnv', 'Name', 'SyncGlobalEnv'),
	('FactorySyncGlobalEnv', 'Description', '同步全局環境配置'),
	('FactorySyncGlobalEnv', 'CronExpression', '0 */10 * * * *'),
	('FactorySyncGlobalPDU', 'Enable', 'true'),
	('FactorySyncGlobalPDU', 'Name', 'SyncGlobalPDU'),
	('FactorySyncGlobalPDU', 'Description', '同步全局 PDU 名單'),
	('FactorySyncGlobalPDU', 'CronExpression', '0 */10 * * * *'),
	('FactorySyncGlobalRule', 'Enable', 'false'),
	('FactorySyncGlobalRule', 'Name', 'SyncGlobalRule'),
	('FactorySyncGlobalRule', 'Description', '同步告警規則'),
	('FactorySyncGlobalRule', 'CronExpression', '0 */10 * * * *'),
    ('FactorySyncGlobalJob', 'Enable', 'true'),
	('FactorySyncGlobalJob', 'Name', 'SyncGlobalJob'),
	('FactorySyncGlobalJob', 'Description', '同步全局 Job 名單'),
	('FactorySyncGlobalJob', 'CronExpression', '0 */10 * * * *'),
    ('FactorySyncGlobalLog', 'Enable', 'true'),
	('FactorySyncGlobalLog', 'Name', 'SyncGlobalLog'),
	('FactorySyncGlobalLog', 'Description', '同步全局 Log 名單'),
	('FactorySyncGlobalLog', 'CronExpression', '0 */10 * * * *'),
	('FactoryRecoverDCData', 'Enable', 'true'),
	('FactoryRecoverDCData', 'Name', 'RecoverDCData'),
	('FactoryRecoverDCData', 'Description', '重傳失敗的 DC 資料'),
	('FactoryRecoverDCData', 'CronExpression', '0 */1 * * * *'),
	('FactoryFlushDCData', 'Enable', 'true'),
	('FactoryFlushDCData', 'Name', 'FlushDCData'),
	('FactoryFlushDCData', 'Description', '刷新 DC 資料'),
	('FactoryFlushDCData', 'CronExpression', '0 */1 * * * *'),
	('DCSyncGlobalTag', 'Enable', 'true'),
	('DCSyncGlobalTag', 'Name', 'SyncGlobalTag'),
	('DCSyncGlobalTag', 'Description', '同步全局標籤'),
	('DCSyncGlobalTag', 'CronExpression', '30 */10 * * * *'),
	('DCAggregateInfluxDBHourly', 'Enable', 'true'),
	('DCAggregateInfluxDBHourly', 'Name', 'AggregateInfluxDBHourly'),
	('DCAggregateInfluxDBHourly', 'Description', '每小時聚合 InfluxDB 數據'),
	('DCAggregateInfluxDBHourly', 'CronExpression', '30 30 * * * *'),
	('DCAggregateInfluxDBDaily', 'Enable', 'true'),
	('DCAggregateInfluxDBDaily', 'Name', 'AggregateInfluxDBDaily'),
	('DCAggregateInfluxDBDaily', 'Description', '每日聚合 InfluxDB 數據'),
	('DCAggregateInfluxDBDaily', 'CronExpression', '0 40 2 * * *'),
	('DCBackupInfluxDB', 'Enable', 'true'),
	('DCBackupInfluxDB', 'Name', 'BackupInfluxDB'),
	('DCBackupInfluxDB', 'Description', '備份 InfluxDB 數據'),
	('DCBackupInfluxDB', 'CronExpression', '0 20 4 * * *'),
	('DCOutputSQLServerMinute', 'Enable', 'true'),
	('DCOutputSQLServerMinute', 'Name', 'OutputSQLServerMinute'),
	('DCOutputSQLServerMinute', 'Description', '每 10 分鐘輸出 SQLServer 數據'),
	('DCOutputSQLServerMinute', 'CronExpression', '0 5,15,25,35,45,55 * * * *'),
	('DCOutputSQLServerMinute', 'DataRange', '-10m'),
	('DCOutputSQLServerMinute', 'Delay', '10'),
	('DCOutputSQLServerHour', 'Enable', 'true'),
	('DCOutputSQLServerHour', 'Name', 'OutputSQLServerHour'),
	('DCOutputSQLServerHour', 'Description', '每 3 小時輸出 SQLServer 數據'),
	('DCOutputSQLServerHour', 'CronExpression', '0 3,6,9,12,15,18,21 * * * *'),
	('DCOutputSQLServerHour', 'DataRange', '-3h'),
	('DCOutputSQLServerHour', 'Delay', '180'),
	('DCOutputSQLServerHour', 'Aggregate', '10m'),
	('DCOutputSQLServerEvent', 'Enable', 'true'),
	('DCOutputSQLServerEvent', 'Name', 'OutputSQLServerEvent'),
	('DCOutputSQLServerEvent', 'Description', '每 10 分鐘輸出 SQLServer 事件數據'),
	('DCOutputSQLServerEvent', 'CronExpression', '0 5,15,25,35,45,55 * * * *'),
	('DCOutputSQLServerEvent', 'DataRange', '-10m'),
	('DCOutputSQLServerEvent', 'Delay', '10'),
	('DCRecoverInfluxDBData', 'Enable', 'true'),
	('DCRecoverInfluxDBData', 'Name', 'RecoverInfluxDBData'),
	('DCRecoverInfluxDBData', 'Description', '重傳未成功寫入 InfluxDB 的數據'),
	('DCRecoverInfluxDBData', 'CronExpression', '0 */3 * * * *'),
	('DCFlushInfluxDBData', 'Enable', 'true'),
	('DCFlushInfluxDBData', 'Name', 'FlushInfluxDBData'),
	('DCFlushInfluxDBData', 'Description', '定期刷新 InfluxDB 數據'),
	('DCFlushInfluxDBData', 'CronExpression', '0 */10 * * * *')